# Generated by Django 5.1.4 on 2024-12-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Teacher Name')),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('about', models.TextField(blank=True, verbose_name='About')),
                ('qualifications', models.TextField(verbose_name='Qualifications')),
                ('experience', models.PositiveIntegerField(verbose_name='Years of Experience')),
                ('projects', models.TextField(blank=True, verbose_name='Projects')),
                ('others', models.TextField(blank=True, verbose_name='Other Achievements')),
                ('conferences', models.TextField(blank=True, verbose_name='Conferences Attended')),
                ('journals', models.TextField(blank=True, verbose_name='Journals Published')),
            ],
        ),
    ]
