# Generated by Django 5.1.4 on 2024-12-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Researcher Name')),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('research_interests', models.TextField(verbose_name='Research Interests')),
                ('research_scholars', models.TextField(verbose_name='Research Scholars')),
                ('projects', models.TextField(verbose_name='Projects')),
                ('image', models.ImageField(blank=True, null=True, upload_to='research_images/', verbose_name='Profile Image')),
                ('publications', models.TextField(blank=True, verbose_name='Publications')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='branch',
            field=models.CharField(default='General', max_length=255, verbose_name='Branch Name'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers_images/'),
        ),
    ]
