# Generated by Django 5.1.4 on 2024-12-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_research_teacher_branch_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='conferences',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='journals',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='others',
        ),
        migrations.AddField(
            model_name='teacher',
            name='path',
            field=models.CharField(default='\\home', max_length=255, verbose_name='Path'),
        ),
    ]
