# Generated by Django 5.1.7 on 2025-03-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Subject Name')),
                ('description', models.TextField(blank=True, verbose_name='Subject Description')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.class', verbose_name='Assigned Class')),
            ],
        ),
        migrations.DeleteModel(
            name='ClassEnrollment',
        ),
    ]
