# Generated by Django 5.1.7 on 2025-03-23 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_class_students_subject_delete_classenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Exam Name')),
                ('description', models.TextField(blank=True, verbose_name='Exam Description')),
                ('exam_date', models.DateField(verbose_name='Exam Date')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.class', verbose_name='Assigned Class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.subject', verbose_name='Subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_marks', models.JSONField(default=dict, verbose_name='Student Marks')),
                ('total_marks', models.PositiveIntegerField(verbose_name='Total Marks')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.exam', verbose_name='Exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='api.subject', verbose_name='Subject')),
            ],
        ),
    ]
