# Generated by Django 5.1.7 on 2025-03-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_exam_examresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_date',
        ),
    ]
