# Generated by Django 5.1.7 on 2025-03-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_exam_exam_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='student_marks',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='examresult',
            name='results',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='api.exam'),
            preserve_default=False,
        ),
    ]
