# Generated by Django 5.1.7 on 2025-03-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_placementprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="placementprofile",
            name="is_placement_coordinator",
            field=models.BooleanField(default=False),
        ),
    ]
