# Generated by Django 5.1.7 on 2025-03-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_placementprofile_percentage_10th_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placementcompany",
            name="min_10th",
            field=models.FloatField(default=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="placementcompany",
            name="min_12th",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="placementcompany",
            name="min_cgpa",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="placementprofile",
            name="percentage_10th",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="placementprofile",
            name="percentage_12th",
            field=models.FloatField(),
        ),
    ]
