# Generated by Django 5.1.7 on 2025-04-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_placementcompany_min_10th_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placementcompany",
            name="package",
            field=models.IntegerField(default=800000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="placementprofile",
            name="cgpa",
            field=models.FloatField(),
        ),
    ]
