# Generated by Django 5.1.7 on 2025-04-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_placementcompany_package_alter_placementprofile_cgpa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placementapplication",
            name="resume",
        ),
    ]
