# Generated by Django 5.1.7 on 2025-04-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_placementapplication_company_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="placementapplication",
            old_name="company_id",
            new_name="company",
        ),
    ]
